### ISSUE TITLE
Links not accessible on pyATS Genie Documentation 

### ISSUE THREAD

**Issue by stefanopilla** [CiscoTestAutomation/genie#110]
Hi,

the links on the pyATS Genie documentation here  https://pubhub.devnetcloud.com/media/genie-docs/docs/cookbooks/ops.html
are not accessible from external users.

Can you please open the access or provide an alternative link ?

Thank you

**Comment by sowmyadn010501** [comment]
Hello stefanopilla,
I am working on this issue, Please give us some time to find out the issue.

**Comment by sowmyadn010501** [comment]
Hello stefanopilla,
our is looking in to your issue, i will let you know once i get the update.

**Comment by sowmyadn010501** [comment]
Hello stefanopilla,
we are looking into your issue, i will let you know once i get the update.

**Comment by sowmyadn010501** [comment]
Hi, I have created the [jira](https://miggbo.atlassian.net/browse/DEVX-21762) for this. Hence i will be closing this issue. Kindly follow up [jira](https://miggbo.atlassian.net/browse/DEVX-21762).

**Comment by sowmyadn010501** [comment]
[sowmyadn010501](https://github.com/sowmyadn010501) commented [now](https://github.com/CiscoTestAutomation/genie/issues/110#issuecomment-1976388642)
Hi, I have created the [jira](https://miggbo.atlassian.net/browse/DEVX-21762) for this. Hence i will be closing this issue. Kindly follow up [jira](https://miggbo.atlassian.net/browse/DEVX-21762).
