### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by etiedem** [CiscoTestAutomation/genie#41]
First of all this is a brilliant feature that is extremely useful; however, I could not find anywhere in the documentation that actually shows how to use it. Only a list of available APIs and the guidelines for creating new ones. I was lucky enough to find an API that called another API to see that you simply add ".api" to the device object.

**Comment by tahigash** [comment]
@etiedem thanks for your feedback! actually, we have below page to show how to use device API.

https://pubhub.devnetcloud.com/media/genie-docs/docs/cookbooks/explore.html#device-api-functions

Please let us know if any other good place to add.

**Comment by tahigash** [comment]
closing this issue. please let us know if you have any better place to add in doc. and feel free to re-open if you need.
